# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVz4TXPK55oXogZJfXbdZseJkJOwqNYC
"""

!pip install transformers

from transformers import pipeline

# Carregar o modelo de IA generativa
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B')

# Função para receber entradas do usuário e gerar uma história
def gerar_historia():
    # Coletando dados do usuário
    nome_personagem = input("Digite o nome do personagem principal: ")
    tema = input("Qual o tema da história (aventura, mistério, comédia)? ")
    cidade = input("Onde a história acontece (ex: cidade misteriosa, floresta sombria)? ")

    # Criando o prompt com base nas entradas do usuário
    prompt = f"Crie uma história de {tema} onde o personagem principal é {nome_personagem}, e a história acontece em {cidade}. "

    # Gerar a história com a IA
    historia = generator(prompt, max_length=250, truncation=True, pad_token_id=50256)

    # Exibir a história gerada
    print("\nHistória gerada: ")
    print(historia[0]['generated_text'])

# Chama a função para gerar a história
gerar_historia()